PAGE_HOME = 'https://qa-scooter.praktikum-services.ru/'
PAGE_CREATE_COURIER = f'{PAGE_HOME}api/v1/courier'
PAGE_LOGIN_COURIER = f'{PAGE_HOME}api/v1/courier/login'
PAGE_ORDER_CREATE = f'{PAGE_HOME}api/v1/orders'
PAGE_ORDER_LIST = f'{PAGE_HOME}api/v1/orders'